language: php

cache:
  directories:
  - vendor

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --verbose --coverage-clover=coverage.clover --coverage-html coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  email: helios.ag@gmail.com
