language: php

php:
  - 5.3.10
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php:
      - hhvm
      - 7.0
  fast_finish: true

install:
    - composer self-update

script: phpunit --coverage-clover=clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  email: helios.ag@gmail.com
