language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php:
      - hhvm
      - 7.0
  fast_finish: true

before_script: 
  - travis_retry composer self-update
  - travis_retry composer install --dev --prefer-source

notifications:
  email: helios.ag@gmail.com
